<?php
namespace DHP_FW\cache;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-16 at 22:14:56.
 */
class CacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Cache(new Apc());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     */
    public function testBucket()
    {
        $cacheBucket = $this->object->bucket('soemting');
        \PHPUnit_Framework_Assert::assertInstanceOf('DHP_FW\\cache\\CacheBucketProxy',$cacheBucket);

        $cacheBucket->set('henrik','pejer');
        $cacheBucket->set('verify',TRUE);
        \PHPUnit_Framework_Assert::assertEquals('pejer',$cacheBucket->get('henrik'));
        \PHPUnit_Framework_Assert::assertEquals('pejer',apc_fetch('soemting_henrik'));

        $cacheBucket->delete('henrik');
        \PHPUnit_Framework_Assert::assertFalse($cacheBucket->get('henrik'));
        $cacheBucket->flush();
        \PHPUnit_Framework_Assert::assertFalse($cacheBucket->get('verify'));

    }
}
