<?php
namespace DHP_FW;
use DHP_FW\Response;
use DHP_FW\Request;
use DHP_FW\Event;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-14 at 21:57:37.
 */
class ControllerTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->e      = new Event();
        $this->object = new Controller(new Request(), new Response($this->e), $this->e);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @covers DHP_FW\Controller::__eventCatchall
     */
    public function test__eventCatchall() {
        $mock = $this->getMock('DHP_FW\\Controller',array(),array(new Request(),new Response($this->e), $this->e));
        $mock->expects($this->exactly(1))->method('__eventCatchall');
        $e = 'something';
        #$this->expectOutputString('hell!');
        $this->e->register('something', function () {
            }
        );
        $this->e->trigger('something', $e);
    }
}
