<?php
namespace DHP_FW;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-05 at 20:05:43.
 */
class LogTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Log
     */
    protected $object;
    protected $logFile;

    public function __construct(){
        $this->logFile = __DIR__.'/logTest.txt';
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Log(new \DHP_FW\storage\File($this->logFile),new Event());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unlink($this->logFile);
    }

    public function testLog() {
        $this->object->message('Test log');
        \PHPUnit_Framework_Assert::assertContains('Test log',file_get_contents($this->logFile));
    }

    public function testLogWithCategories() {
        $this->object->message('Test log','DEBUG');
        \PHPUnit_Framework_Assert::assertContains('DEBUG]::Test log',file_get_contents($this->logFile));
        $this->object->message('Test log','DEBUG','SOMETHING','OROTHER');
        \PHPUnit_Framework_Assert::assertContains('DEBUG|SOMETHING|OROTHER]::Test log',file_get_contents($this->logFile));
    }
}
