<?php
namespace DHP_FW\middleware;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-01 at 15:10:08.
 */
class ParseRequestBodyTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var ParseRequestBody
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $_SERVER['HTTP_CONTENT_TYPE'] = 'Application/json: encoding=utf8';
        $this->request                = new \DHP_FW\Request( NULL, NULL,
                                                             '{"henrik":"pejer"}' );
        $this->object                 = new ParseRequestBody( $this->request );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function testJsonParsing() {
        \PHPUnit_Framework_Assert::assertEquals('pejer',
                                                $this->request->body->henrik);
    }

    public function testMiddlewareLoading(){
        $_SERVER['HTTP_CONTENT_TYPE'] = 'Application/json: encoding=utf8';
        $this->request                = new \DHP_FW\Request( NULL, NULL,
                                                             '{"henrik":"pejer"}' );
        \PHPUnit_Framework_Assert::assertEquals('{"henrik":"pejer"}',
                                                $this->request->body);
        $this->object = new ParseRequestBody( $this->request );
        \PHPUnit_Framework_Assert::assertEquals('pejer',
                                                $this->request->body->henrik);
    }

    public function testWrongContentType() {
        $_SERVER['HTTP_CONTENT_TYPE'] = 'Application/jso: encoding=utf8';
        $this->request                = new \DHP_FW\Request( NULL, NULL,
                                                             '{"henrik":"pejer"}' );
        \PHPUnit_Framework_Assert::assertEquals('{"henrik":"pejer"}',
                                                $this->request->body);
        $this->object = new ParseRequestBody( $this->request );
        \PHPUnit_Framework_Assert::assertEquals('{"henrik":"pejer"}',
                                                $this->request->body);

    }
}
