<?php
namespace DHP_FW\middleware;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-20 at 00:37:09.
 */
class SessionTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Session
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->e      = new \DHP_FW\Event();
        $this->object = new Session(new \DHP_FW\Request('GET','/',NULL,$this->e));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }


    public function testDataChanged() {
        \PHPUnit_Framework_Assert::assertNull($this->object->flash->henrik);
        \PHPUnit_Framework_Assert::assertAttributeEquals(FALSE,'dataChanged',$this->object);
        $this->object->flash->henrik = 'pejer';
        \PHPUnit_Framework_Assert::assertEquals('pejer',$this->object->flash->henrik);
        #\PHPUnit_Framework_Assert::assertAttributeEquals(TRUE,'dataChanged',$this->object);
    }
    public function test__set() {
        \PHPUnit_Framework_Assert::assertNull($this->object->henrik);
        $this->object->henrik = 'pejer';
        \PHPUnit_Framework_Assert::assertEquals('pejer', $this->object->henrik);
    }

    public function test__get() {
        \PHPUnit_Framework_Assert::assertNull($this->object->henrik);
        $this->object->henrik = 'pejer';
        \PHPUnit_Framework_Assert::assertEquals('pejer', $this->object->henrik);
    }
}
