<?php
namespace DHP_FW;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-17 at 20:54:25.
 */
class ParameterBagTestReadOnly extends \PHPUnit_Framework_TestCase {
    /**
     * @var ParameterBag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ParameterBagReadOnly(array('some' => 'value'),\app\DI()->get('DHP_FW\EventInterface'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function testGet() {
        \PHPUnit_Framework_Assert::assertEquals('value',$this->object->some);
    }

    public function testSet(){
        \PHPUnit_Framework_Assert::assertEquals('value',$this->object->some);
        $this->object->some = 'new value';
        \PHPUnit_Framework_Assert::assertEquals('value',$this->object->some);
    }
}
