<?php
namespace DHP_FW;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-06 at 09:38:13.
 */
class RequestTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $_SERVER['HTTP_HOST'] = 'phpunittests.com';
        $this->object = new Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function testGenerateMethods() {
        $_SERVER['REQUEST_METHOD'] = 'HEAD';
        $_SERVER['REQUEST_URI']    = '/headcheck';
        $o = new Request();
        \PHPUnit_Framework_Assert::assertEquals('headcheck',$o->getUri());
        \PHPUnit_Framework_Assert::assertEquals('HEAD',$o->getMethod());
        unset($_SERVER['REQUEST_METHOD']);
        unset($_SERVER['REQUEST_URI']);
    }

    public function testHeaders(){
        \PHPUnit_Framework_Assert::assertEquals(array('Host'=>'phpunittests.com'),$this->object->getHeaders());
        \PHPUnit_Framework_Assert::assertEquals('phpunittests.com',$this->object->header('Host'));
    }



    /**
     * @todo   Implement testGetMethod().
     */
    public function testGetMethod() {
        \PHPUnit_Framework_Assert::assertEquals('GET', $this->object->getMethod());
    }

    /**
     * @todo   Implement testSetMethod().
     */
    public function testSetMethod() {
        $this->object->setMethod('POST');
        \PHPUnit_Framework_Assert::assertEquals('POST', $this->object->getMethod());

    }

    /**
     * @covers DHP_FW\Request::setUri
     * @todo   Implement testSetUri().
     */
    public function testSetUri() {
        $this->object->setUri('/working');
        \PHPUnit_Framework_Assert::assertEquals('/working', $this->object->getUri());
    }

    /**
     * @covers DHP_FW\Request::getUri
     * @todo   Implement testGetUri().
     */
    public function testGetUri() {
        \PHPUnit_Framework_Assert::assertEquals('', $this->object->getUri());
    }
}
