<?php
namespace DHP_FW;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-26 at 20:48:26.
 */
class TemplateTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Template
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Template;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }


    public function testSetString() {
        $this->object->setString('Hello {?variableName}world {?name}{?anotherOptionalVariable}');
        $this->object->setData(array('name' => 'henrik'));
        $data = $this->object->render();
        \PHPUnit_Framework_Assert::assertEquals('Hello world henrik', $data);
    }

    public function testRepeats(){
        $this->object->setString('<ul>{books}
        <li>{author} => {title} {sub}{something}{/sub}</li>
{/books}</ul>');
        $books = array('books' => array(
            array('author' => 'Henrik', 'title' => 'First book', 'sub' => array(
                array('something' => 'one')

            )),
            array('author' => 'Henrik Pejer', 'title' => 'Second book', 'sub' => array(
                array('something' => 'two'),
                array('something' => 'three')

            )))
        );
        $this->object->setData($books);

        $matchAgainst = '<ul>
        <li>Henrik => First book one</li>

        <li>Henrik Pejer => Second book twothree</li>
</ul>';
        \PHPUnit_Framework_Assert::assertEquals($matchAgainst,$this->object->render());
    }

    public function testSetFile(){
        $templateFile = __DIR__.'/template.tpl';
        touch($templateFile);
        $fh = fopen($templateFile,'w+');
        fwrite($fh,'{name}');
        fclose($fh);
        $this->object->setFile($templateFile);
        \DHP_FW\Template::globalData(array('name' => 'Henrik'));
        \PHPUnit_Framework_Assert::assertEquals('Henrik',$this->object->render());
        $this->object->setData(array('name' => 'Henrik Pejer'));
        \PHPUnit_Framework_Assert::assertEquals('Henrik Pejer',$this->object->render());
        \PHPUnit_Framework_Assert::assertEquals('Henrik Pejer',$this->object->render(array('name' => 'Dag Henrik Pejer')));
        unlink($templateFile);
    }
}
